// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpxYl2xPwf8mqesYUENxaMpAn2bxVQPg',
    appId: '1:866008257966:android:a5d4ba7f3284e62827e43f',
    messagingSenderId: '866008257966',
    projectId: 'proyectointegradojg2024',
    storageBucket: 'proyectointegradojg2024.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi8rbBU8GRo6tdNV0dfbchc-fsACXdg7U',
    appId: '1:866008257966:web:695ed4c8a0c7e35627e43f',
    messagingSenderId: '866008257966',
    projectId: 'proyectointegradojg2024',
    authDomain: 'proyectointegradojg2024.firebaseapp.com',
    storageBucket: 'proyectointegradojg2024.firebasestorage.app',
    measurementId: 'G-3LEJQBRM6V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi8rbBU8GRo6tdNV0dfbchc-fsACXdg7U',
    appId: '1:866008257966:web:695ed4c8a0c7e35627e43f',
    messagingSenderId: '866008257966',
    projectId: 'proyectointegradojg2024',
    authDomain: 'proyectointegradojg2024.firebaseapp.com',
    storageBucket: 'proyectointegradojg2024.firebasestorage.app',
    measurementId: 'G-3LEJQBRM6V',
  );

}